### ISSUE TITLE
objects show as [object Object]

### ISSUE THREAD

**Issue by alepouna** [rvdende/surrealreact#1]
As the title suggests, if storing an object in a row, example this is what we store in "users.information" 
```js
{
name: 'username',
anothertest: true,
numeric: 10
}
```
will display in the browser as [object Object]
![msedge_goqXGHeYfb](https://user-images.githubusercontent.com/98479040/196279644-7a371bd3-1db1-4093-983c-28e313e585ff.png)

**Comment by rvdende** [comment]
Hi @auroraisluna :) I just fixed this for you. It should be going live in version 0.1.15 as soon as the deployment is done.

Here is the commit: https://github.com/rvdende/surrealreact/commit/09b8afee29795eb5ebf227ead5e6b9b48aac93b5

Screenshot:
![Screenshot 2022-10-18 at 16 23 59](https://user-images.githubusercontent.com/3116694/196457943-751b8e45-fb39-4d1a-91d2-9b1552acf6f1.png)
