### ISSUE TITLE
[Feat] Simple editting

### ISSUE THREAD

**Issue by alepouna** [rvdende/surrealreact#2]
Would be really cool if there was some very simple way to just click on a field and allow to edit it online. Nothing complicated, nothing fancy. Even a javascript:alert() prompt works 😅

**Comment by rvdende** [comment]
See https://github.com/rvdende/surrealreact/pull/5
Clicking on a table row now opens the data entry in a monaco editor in the browser, this then allows json editing of the row however saving changes still need to be implemented. Just need to add a simple save button I guess.

**Comment by rvdende** [comment]
https://github.com/rvdende/surrealreact/pull/6

**Comment by rvdende** [comment]
can now click on a table row and edit the json and save back to update.
