### ISSUE TITLE
RPC connections fail with Surreal beta.8 / nightly

### ISSUE THREAD

**Issue by itsezc** [rvdende/surrealreact#3]
Tried on Windows and Mac, SurrealReact fails to connect to nightly builds with the RPC server and no error message is prompted, direct access via `/sql` and `/rpc` with other tools does work.

**Comment by rvdende** [comment]
Did you self host or use the online instance? Beta8 works fine for me. Make sure you use the http url if connecting to a non ssl/tsl instance.

**Comment by itsezc** [comment]
Its a self hosted instance on localhost, worked previously on Beta 7 and the details are the exact same, I'll try debugging a little and update you with any further information

**Comment by rvdende** [comment]
You can also try to clear app data or use incognito this will clear out settings from localstorage.

**Comment by itsezc** [comment]
I've cleared app data, used incognito and tried the following platforms:

- MacOS x64 Surreal Beta  8
- Windows 11 (WSL - Ubuntu 20.04) Surreal Beta 8

Browsers:

- Firefox Developer Edition 107
- Chrome 107

Network log:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/33750251/201271255-1c8226fe-4d6e-4928-857d-871a56912d97.png">

Via a HTTP Client - using the `/sql` endpoint:
<img width="1850" alt="image" src="https://user-images.githubusercontent.com/33750251/201271397-251710ae-87d2-4f7d-ae44-5da5dce950fe.png">

Exact build of Surreal: `1.0.0-beta.8+20221102.f3c9a9a`

**Comment by itsezc** [comment]
Tried on HTTP url, still no luck, unfortunately.

**Comment by itsezc** [comment]
> Did you self host or use the online instance? Beta8 works fine for me. Make sure you use the http url if connecting to a non ssl/tsl instance.

Issue is consistently present in nightly, not any of the beta releases.

**Comment by rvdende** [comment]
If so then something must be different in the nightly build. I've become a bit busy on other projects right now so can't follow up at the moment.

**Comment by rvdende** [comment]
The new version resolves connection issues. App now uses http instead of the websockets for reliability, looks like there was some subtle change that caused the issue above.
